apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dtg3phchy-python
  janus-idp.io/tekton: dtg3phchy-python
  backstage.io/kubernetes-id: dtg3phchy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dtg3phchy-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
