apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dtg3phchy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dtg3phchy-python 
  name: dtg3phchy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dtg3phchy-python 
